# docker/visualizer/Dockerfile
# Passthrough component: visualizer ships only what is already in upstream
# universe.

# hadolint ignore=DL3006
ARG UPSTREAM_DEVEL
ARG UPSTREAM_RUN
ARG ROS_DISTRO=jazzy

FROM ${UPSTREAM_RUN} AS visualizer
