source.input_camera_topic   = /carla/hero/main_cam/image
vehicle_speed_topic         = /vehicle/speed
vehicle_steering_topic      = /vehicle/steering_cmd
vehicle_acceleration_topic  = /vehicle/throttle_cmd
